# Generated by Django 3.1.1 on 2020-09-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
