# Generated by Django 3.1.1 on 2020-09-24 08:14

import apps.ofertas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0003_auto_20200924_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenoferta',
            name='imagen',
            field=models.ImageField(blank=True, default='img/ofertas/por_defecto/oferta-img.jpg', null=True, upload_to=apps.ofertas.models.get_image_path),
        ),
    ]
