# Generated by Django 3.1.1 on 2020-09-24 08:16

import apps.ofertas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0004_auto_20200924_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='imagen_portada',
            field=models.ImageField(blank=True, default='img/ofertas/por_defecto/oferta-img.jpg', null=True, upload_to=apps.ofertas.models.get_image_path),
        ),
    ]
