# Generated by Django 3.1.1 on 2020-09-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_auto_20200928_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, default='en espera', null=True),
        ),
    ]
