# Generated by Django 3.1.1 on 2020-09-28 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ofertas', '0007_auto_20200928_0348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('en espera', 'En espera'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], max_length=15)),
                ('contratado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_recibidos', to=settings.AUTH_USER_MODEL)),
                ('contratante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_hechos', to=settings.AUTH_USER_MODEL)),
                ('oferta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos', to='ofertas.oferta')),
            ],
        ),
    ]
