# Generated by Django 3.1.1 on 2020-09-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0005_auto_20200928_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='estado',
            field=models.CharField(default='en espera', max_length=15),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
