# Generated by Django 3.1.1 on 2020-09-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0007_auto_20200928_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='precio',
            field=models.IntegerField(null=True),
        ),
    ]
