# Generated by Django 3.1.1 on 2020-09-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('contratos', '0008_contrato_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='categorias',
            field=models.ManyToManyField(blank=True, to='categorias.Categoria'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='puntaje',
            field=models.IntegerField(blank=True, choices=[(1, 'Malo'), (2, 'Regular'), (3, 'Pasable'), (4, 'Bueno'), (5, 'Excelente')], default=None, null=True),
        ),
    ]
