# Generated by Django 3.1.1 on 2020-09-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='categorias',
            field=models.ManyToManyField(related_name='perfiles', to='categorias.Categoria'),
        ),
    ]
