# Generated by Django 3.1.1 on 2020-09-14 05:41

from django.db import migrations, models
import django.db.models.deletion
import perfiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, default='img/perfiles/empty-profile.png', null=True, upload_to=perfiles.models.get_image_path)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas.usuario')),
            ],
            options={
                'verbose_name_plural': 'Perfiles',
            },
        ),
    ]
