# Generated by Django 3.1.1 on 2020-09-14 06:03

from django.db import migrations, models
import perfiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, default='static/img/perfiles/empty-profile.png', null=True, upload_to=perfiles.models.get_image_path),
        ),
    ]
