# Generated by Django 3.1.1 on 2020-09-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('ofertas', '0004_remove_oferta_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='categorias',
            field=models.ManyToManyField(related_name='ofertas', to='categorias.Categoria'),
        ),
    ]
