# Generated by Django 3.1.1 on 2020-09-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('ofertas', '0005_oferta_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='categorias',
            field=models.ManyToManyField(blank=True, null=True, related_name='ofertas', to='categorias.Categoria'),
        ),
    ]
