# Generated by Django 3.1.1 on 2020-09-23 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posteo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posteo',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='posteo',
            name='content',
        ),
        migrations.RemoveField(
            model_name='posteo',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='posteo',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='posteo',
            name='thumbmail',
        ),
        migrations.RemoveField(
            model_name='posteo',
            name='title',
        ),
    ]
