# Generated by Django 3.1.1 on 2020-09-28 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0002_auto_20200928_0231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oferta',
            old_name='categoria',
            new_name='categorias',
        ),
    ]
