# Generated by Django 3.1.1 on 2020-09-28 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0003_auto_20200928_0243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='categorias',
        ),
    ]
